GET http://localhost:4000/

###

POST http://localhost:4000/register
content-type: application/json

{
    "username": "kimi",
    "password": "ona"
}

###

POST http://localhost:4000/login
content-type: application/json

{
    "username": "kimi",
    "password": "ona"
}